language: scala
scala:
  - 2.11.8
  - 2.10.6

jdk:
  - oraclejdk8
  - oraclejdk7

before_script: sh .travis_script.sh
script:
  - sbt ++2.11.8 test
  - sbt +clean
  - sbt ++2.10.6 test

sudo: required

#services:
#  - docker

#env:
#  - DOCKER_HOST=unix:///var/run/docker.sock

#addons:
#  hosts:
#    - dockerhost
