# use containers
sudo: false

language: scala
scala:
  - 2.12.10
  - 2.11.12
  - 2.10.7

jdk:
  - openjdk8

env:
  - CASSANDRA_DRIVER_VERSION=3.5.0
  - CASSANDRA_DRIVER_VERSION=2.1.10.3

sbt_args: -Dcassandra-driver.version=$CASSANDRA_DRIVER_VERSION

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_script: 
  - mkdir lib
  - wget https://github.com/Ichoran/thyme/raw/master/Thyme.jar -O lib/Thyme.jar

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b37d78d8e7cb1d34adb3
