language: scala
scala:
  - 2.11.8
  - 2.10.6

jdk:
  - oraclejdk8
  - oraclejdk7

before_script: sh .travis_script.sh

sudo: required

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b37d78d8e7cb1d34adb3

#services:
#  - docker

#env:
#  - DOCKER_HOST=unix:///var/run/docker.sock

#addons:
#  hosts:
#    - dockerhost
