language: scala
scala:
  - 2.11.8

jdk:
  - oraclejdk8
  - oraclejdk7

before_script: sh .travis_script.sh
script: sbt +test

sudo: required

#services:
#  - docker

#env:
#  - DOCKER_HOST=unix:///var/run/docker.sock

#addons:
#  hosts:
#    - dockerhost
